title: NVIDIA Tech Guides
description: >
  A knowledge-sharing site for NVIDIA technology learnings by Saravanan Gnanaguru
  (https://gsaravanan.dev), part of the NVIDIA Developer Program.
baseurl: "/nvidia_tech_guides"
url: "https://chefgs.github.io"

theme: minima

author:
  name: Saravanan Gnanaguru
  url: https://gsaravanan.dev

header_pages:
  - nvidia-nim/index.md
  - nvidia-tensorrt/index.md
  - nvidia-triton/index.md
  - nvidia-nemo/index.md
  - nvidia-cuda/index.md
  - nvidia-rapids/index.md
  - nvidia-cudnn/index.md
  - nvidia-api-catalog/index.md
  - ai-trends/index.md

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
